package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentRole;
import com.hero.wireless.web.entity.business.AgentRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentRoleDAO<T extends AgentRole> extends IDao<AgentRole, AgentRoleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int countByExample(AgentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int deleteByExample(AgentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int insert(AgentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int insertList(List<AgentRole> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int insertSelective(AgentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    List<AgentRole> selectByExample(AgentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    AgentRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentRole record, @Param("example") AgentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int updateByExample(@Param("record") AgentRole record, @Param("example") AgentRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int updateByPrimaryKeySelective(AgentRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_role
     *
     * @mbg.generated Tue Oct 19 10:30:10 CST 2021
     */
    int updateByPrimaryKey(AgentRole record);
}