package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentProduct;
import com.hero.wireless.web.entity.business.AgentProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentProductDAO<T extends AgentProduct> extends IDao<AgentProduct, AgentProductExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int countByExample(AgentProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int deleteByExample(AgentProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int insert(AgentProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int insertList(List<AgentProduct> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int insertSelective(AgentProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    List<AgentProduct> selectByExample(AgentProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    AgentProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentProduct record, @Param("example") AgentProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int updateByExample(@Param("record") AgentProduct record, @Param("example") AgentProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int updateByPrimaryKeySelective(AgentProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_product
     *
     * @mbg.generated Tue Oct 19 10:30:00 CST 2021
     */
    int updateByPrimaryKey(AgentProduct record);
}