package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.Agent;
import com.hero.wireless.web.entity.business.AgentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentDAO<T extends Agent> extends IDao<Agent, AgentExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int countByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int deleteByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int insert(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int insertList(List<Agent> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int insertSelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    List<Agent> selectByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    Agent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") Agent record, @Param("example") AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int updateByExample(@Param("record") Agent record, @Param("example") AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int updateByPrimaryKeySelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    int updateByPrimaryKey(Agent record);
}