package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentLimit;
import com.hero.wireless.web.entity.business.AgentLimitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentLimitDAO<T extends AgentLimit> extends IDao<AgentLimit, AgentLimitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int countByExample(AgentLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int deleteByExample(AgentLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int insert(AgentLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int insertList(List<AgentLimit> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int insertSelective(AgentLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    List<AgentLimit> selectByExample(AgentLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    AgentLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentLimit record, @Param("example") AgentLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int updateByExample(@Param("record") AgentLimit record, @Param("example") AgentLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int updateByPrimaryKeySelective(AgentLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_limit
     *
     * @mbg.generated Tue Oct 19 10:29:51 CST 2021
     */
    int updateByPrimaryKey(AgentLimit record);
}