package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentRoles;
import com.hero.wireless.web.entity.business.AgentRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentRolesDAO<T extends AgentRoles> extends IDao<AgentRoles, AgentRolesExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int countByExample(AgentRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int deleteByExample(AgentRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int insert(AgentRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int insertList(List<AgentRoles> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int insertSelective(AgentRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    List<AgentRoles> selectByExample(AgentRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    AgentRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentRoles record, @Param("example") AgentRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int updateByExample(@Param("record") AgentRoles record, @Param("example") AgentRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int updateByPrimaryKeySelective(AgentRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_roles
     *
     * @mbg.generated Tue Oct 19 10:30:36 CST 2021
     */
    int updateByPrimaryKey(AgentRoles record);
}