package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentFee;
import com.hero.wireless.web.entity.business.AgentFeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentFeeDAO<T extends AgentFee> extends IDao<AgentFee, AgentFeeExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int countByExample(AgentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int deleteByExample(AgentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int insert(AgentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int insertList(List<AgentFee> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int insertSelective(AgentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    List<AgentFee> selectByExample(AgentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    AgentFee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentFee record, @Param("example") AgentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int updateByExample(@Param("record") AgentFee record, @Param("example") AgentFeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int updateByPrimaryKeySelective(AgentFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_fee
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    int updateByPrimaryKey(AgentFee record);
}