package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AgentCharge;
import com.hero.wireless.web.entity.business.AgentChargeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAgentChargeDAO<T extends AgentCharge> extends IDao<AgentCharge, AgentChargeExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int countByExample(AgentChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int deleteByExample(AgentChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int insert(AgentCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int insertList(List<AgentCharge> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int insertSelective(AgentCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    List<AgentCharge> selectByExample(AgentChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    AgentCharge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int updateByExampleSelective(@Param("record") AgentCharge record, @Param("example") AgentChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int updateByExample(@Param("record") AgentCharge record, @Param("example") AgentChargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int updateByPrimaryKeySelective(AgentCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_charge
     *
     * @mbg.generated Tue Oct 19 10:28:54 CST 2021
     */
    int updateByPrimaryKey(AgentCharge record);
}