package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class Agent extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Id
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.User_Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String user_Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Password
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Status
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Type_Code
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Byte type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Product_No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String product_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Domain
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Login_Url
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String login_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Sent_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Integer sent_Count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Used_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private BigDecimal used_Amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Available_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private BigDecimal available_Amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Last_Login_Time
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Date last_Login_Time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Last_Login_IP
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String last_Login_IP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Login_Faild_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Integer login_Faild_Count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Login_Faild_Lock_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Integer login_Faild_Lock_Count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Description
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Remark
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Id
     *
     * @return the value of agent.Id
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Id
     *
     * @param id the value for agent.Id
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.No
     *
     * @return the value of agent.No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.No
     *
     * @param no the value for agent.No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Name
     *
     * @return the value of agent.Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Name
     *
     * @param name the value for agent.Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.User_Name
     *
     * @return the value of agent.User_Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getUser_Name() {
        return user_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.User_Name
     *
     * @param user_Name the value for agent.User_Name
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setUser_Name(String user_Name) {
        this.user_Name = user_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Password
     *
     * @return the value of agent.Password
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Password
     *
     * @param password the value for agent.Password
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Status
     *
     * @return the value of agent.Status
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Status
     *
     * @param status the value for agent.Status
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Type_Code
     *
     * @return the value of agent.Type_Code
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Byte getType_Code() {
        return type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Type_Code
     *
     * @param type_Code the value for agent.Type_Code
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setType_Code(Byte type_Code) {
        this.type_Code = type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Product_No
     *
     * @return the value of agent.Product_No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getProduct_No() {
        return product_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Product_No
     *
     * @param product_No the value for agent.Product_No
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setProduct_No(String product_No) {
        this.product_No = product_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Domain
     *
     * @return the value of agent.Domain
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Domain
     *
     * @param domain the value for agent.Domain
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Login_Url
     *
     * @return the value of agent.Login_Url
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getLogin_Url() {
        return login_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Login_Url
     *
     * @param login_Url the value for agent.Login_Url
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setLogin_Url(String login_Url) {
        this.login_Url = login_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Sent_Count
     *
     * @return the value of agent.Sent_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Integer getSent_Count() {
        return sent_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Sent_Count
     *
     * @param sent_Count the value for agent.Sent_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setSent_Count(Integer sent_Count) {
        this.sent_Count = sent_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Used_Amount
     *
     * @return the value of agent.Used_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public BigDecimal getUsed_Amount() {
        return used_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Used_Amount
     *
     * @param used_Amount the value for agent.Used_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setUsed_Amount(BigDecimal used_Amount) {
        this.used_Amount = used_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Available_Amount
     *
     * @return the value of agent.Available_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public BigDecimal getAvailable_Amount() {
        return available_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Available_Amount
     *
     * @param available_Amount the value for agent.Available_Amount
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setAvailable_Amount(BigDecimal available_Amount) {
        this.available_Amount = available_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Last_Login_Time
     *
     * @return the value of agent.Last_Login_Time
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Date getLast_Login_Time() {
        return last_Login_Time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Last_Login_Time
     *
     * @param last_Login_Time the value for agent.Last_Login_Time
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setLast_Login_Time(Date last_Login_Time) {
        this.last_Login_Time = last_Login_Time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Last_Login_IP
     *
     * @return the value of agent.Last_Login_IP
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getLast_Login_IP() {
        return last_Login_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Last_Login_IP
     *
     * @param last_Login_IP the value for agent.Last_Login_IP
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setLast_Login_IP(String last_Login_IP) {
        this.last_Login_IP = last_Login_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Login_Faild_Count
     *
     * @return the value of agent.Login_Faild_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Integer getLogin_Faild_Count() {
        return login_Faild_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Login_Faild_Count
     *
     * @param login_Faild_Count the value for agent.Login_Faild_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setLogin_Faild_Count(Integer login_Faild_Count) {
        this.login_Faild_Count = login_Faild_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Login_Faild_Lock_Count
     *
     * @return the value of agent.Login_Faild_Lock_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Integer getLogin_Faild_Lock_Count() {
        return login_Faild_Lock_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Login_Faild_Lock_Count
     *
     * @param login_Faild_Lock_Count the value for agent.Login_Faild_Lock_Count
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setLogin_Faild_Lock_Count(Integer login_Faild_Lock_Count) {
        this.login_Faild_Lock_Count = login_Faild_Lock_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Description
     *
     * @return the value of agent.Description
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Description
     *
     * @param description the value for agent.Description
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Remark
     *
     * @return the value of agent.Remark
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Remark
     *
     * @param remark the value for agent.Remark
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.Create_Date
     *
     * @return the value of agent.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.Create_Date
     *
     * @param create_Date the value for agent.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}