package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public AgentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("No is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("No is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("No =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("No <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("No >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("No >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("No <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("No <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("No like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("No not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("No in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("No not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("No between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("No not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUser_NameIsNull() {
            addCriterion("User_Name is null");
            return (Criteria) this;
        }

        public Criteria andUser_NameIsNotNull() {
            addCriterion("User_Name is not null");
            return (Criteria) this;
        }

        public Criteria andUser_NameEqualTo(String value) {
            addCriterion("User_Name =", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameNotEqualTo(String value) {
            addCriterion("User_Name <>", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameGreaterThan(String value) {
            addCriterion("User_Name >", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameGreaterThanOrEqualTo(String value) {
            addCriterion("User_Name >=", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameLessThan(String value) {
            addCriterion("User_Name <", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameLessThanOrEqualTo(String value) {
            addCriterion("User_Name <=", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameLike(String value) {
            addCriterion("User_Name like", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameNotLike(String value) {
            addCriterion("User_Name not like", value, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameIn(List<String> values) {
            addCriterion("User_Name in", values, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameNotIn(List<String> values) {
            addCriterion("User_Name not in", values, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameBetween(String value1, String value2) {
            addCriterion("User_Name between", value1, value2, "user_Name");
            return (Criteria) this;
        }

        public Criteria andUser_NameNotBetween(String value1, String value2) {
            addCriterion("User_Name not between", value1, value2, "user_Name");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andType_CodeIsNull() {
            addCriterion("Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andType_CodeIsNotNull() {
            addCriterion("Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andType_CodeEqualTo(Byte value) {
            addCriterion("Type_Code =", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotEqualTo(Byte value) {
            addCriterion("Type_Code <>", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeGreaterThan(Byte value) {
            addCriterion("Type_Code >", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("Type_Code >=", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeLessThan(Byte value) {
            addCriterion("Type_Code <", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeLessThanOrEqualTo(Byte value) {
            addCriterion("Type_Code <=", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeIn(List<Byte> values) {
            addCriterion("Type_Code in", values, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotIn(List<Byte> values) {
            addCriterion("Type_Code not in", values, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeBetween(Byte value1, Byte value2) {
            addCriterion("Type_Code between", value1, value2, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotBetween(Byte value1, Byte value2) {
            addCriterion("Type_Code not between", value1, value2, "type_Code");
            return (Criteria) this;
        }

        public Criteria andProduct_NoIsNull() {
            addCriterion("Product_No is null");
            return (Criteria) this;
        }

        public Criteria andProduct_NoIsNotNull() {
            addCriterion("Product_No is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_NoEqualTo(String value) {
            addCriterion("Product_No =", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoNotEqualTo(String value) {
            addCriterion("Product_No <>", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoGreaterThan(String value) {
            addCriterion("Product_No >", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Product_No >=", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoLessThan(String value) {
            addCriterion("Product_No <", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoLessThanOrEqualTo(String value) {
            addCriterion("Product_No <=", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoLike(String value) {
            addCriterion("Product_No like", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoNotLike(String value) {
            addCriterion("Product_No not like", value, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoIn(List<String> values) {
            addCriterion("Product_No in", values, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoNotIn(List<String> values) {
            addCriterion("Product_No not in", values, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoBetween(String value1, String value2) {
            addCriterion("Product_No between", value1, value2, "product_No");
            return (Criteria) this;
        }

        public Criteria andProduct_NoNotBetween(String value1, String value2) {
            addCriterion("Product_No not between", value1, value2, "product_No");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("Domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("Domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("Domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("Domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("Domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("Domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("Domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("Domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("Domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("Domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("Domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("Domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("Domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("Domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlIsNull() {
            addCriterion("Login_Url is null");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlIsNotNull() {
            addCriterion("Login_Url is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlEqualTo(String value) {
            addCriterion("Login_Url =", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlNotEqualTo(String value) {
            addCriterion("Login_Url <>", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlGreaterThan(String value) {
            addCriterion("Login_Url >", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlGreaterThanOrEqualTo(String value) {
            addCriterion("Login_Url >=", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlLessThan(String value) {
            addCriterion("Login_Url <", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlLessThanOrEqualTo(String value) {
            addCriterion("Login_Url <=", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlLike(String value) {
            addCriterion("Login_Url like", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlNotLike(String value) {
            addCriterion("Login_Url not like", value, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlIn(List<String> values) {
            addCriterion("Login_Url in", values, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlNotIn(List<String> values) {
            addCriterion("Login_Url not in", values, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlBetween(String value1, String value2) {
            addCriterion("Login_Url between", value1, value2, "login_Url");
            return (Criteria) this;
        }

        public Criteria andLogin_UrlNotBetween(String value1, String value2) {
            addCriterion("Login_Url not between", value1, value2, "login_Url");
            return (Criteria) this;
        }

        public Criteria andSent_CountIsNull() {
            addCriterion("Sent_Count is null");
            return (Criteria) this;
        }

        public Criteria andSent_CountIsNotNull() {
            addCriterion("Sent_Count is not null");
            return (Criteria) this;
        }

        public Criteria andSent_CountEqualTo(Integer value) {
            addCriterion("Sent_Count =", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountNotEqualTo(Integer value) {
            addCriterion("Sent_Count <>", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountGreaterThan(Integer value) {
            addCriterion("Sent_Count >", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sent_Count >=", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountLessThan(Integer value) {
            addCriterion("Sent_Count <", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountLessThanOrEqualTo(Integer value) {
            addCriterion("Sent_Count <=", value, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountIn(List<Integer> values) {
            addCriterion("Sent_Count in", values, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountNotIn(List<Integer> values) {
            addCriterion("Sent_Count not in", values, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountBetween(Integer value1, Integer value2) {
            addCriterion("Sent_Count between", value1, value2, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andSent_CountNotBetween(Integer value1, Integer value2) {
            addCriterion("Sent_Count not between", value1, value2, "sent_Count");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountIsNull() {
            addCriterion("Used_Amount is null");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountIsNotNull() {
            addCriterion("Used_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountEqualTo(BigDecimal value) {
            addCriterion("Used_Amount =", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountNotEqualTo(BigDecimal value) {
            addCriterion("Used_Amount <>", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountGreaterThan(BigDecimal value) {
            addCriterion("Used_Amount >", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Used_Amount >=", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountLessThan(BigDecimal value) {
            addCriterion("Used_Amount <", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Used_Amount <=", value, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountIn(List<BigDecimal> values) {
            addCriterion("Used_Amount in", values, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountNotIn(List<BigDecimal> values) {
            addCriterion("Used_Amount not in", values, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Used_Amount between", value1, value2, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andUsed_AmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Used_Amount not between", value1, value2, "used_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountIsNull() {
            addCriterion("Available_Amount is null");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountIsNotNull() {
            addCriterion("Available_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountEqualTo(BigDecimal value) {
            addCriterion("Available_Amount =", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountNotEqualTo(BigDecimal value) {
            addCriterion("Available_Amount <>", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountGreaterThan(BigDecimal value) {
            addCriterion("Available_Amount >", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Available_Amount >=", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountLessThan(BigDecimal value) {
            addCriterion("Available_Amount <", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Available_Amount <=", value, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountIn(List<BigDecimal> values) {
            addCriterion("Available_Amount in", values, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountNotIn(List<BigDecimal> values) {
            addCriterion("Available_Amount not in", values, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Available_Amount between", value1, value2, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andAvailable_AmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Available_Amount not between", value1, value2, "available_Amount");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeIsNull() {
            addCriterion("Last_Login_Time is null");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeIsNotNull() {
            addCriterion("Last_Login_Time is not null");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeEqualTo(Date value) {
            addCriterion("Last_Login_Time =", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeNotEqualTo(Date value) {
            addCriterion("Last_Login_Time <>", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeGreaterThan(Date value) {
            addCriterion("Last_Login_Time >", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Last_Login_Time >=", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeLessThan(Date value) {
            addCriterion("Last_Login_Time <", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeLessThanOrEqualTo(Date value) {
            addCriterion("Last_Login_Time <=", value, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeIn(List<Date> values) {
            addCriterion("Last_Login_Time in", values, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeNotIn(List<Date> values) {
            addCriterion("Last_Login_Time not in", values, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeBetween(Date value1, Date value2) {
            addCriterion("Last_Login_Time between", value1, value2, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_TimeNotBetween(Date value1, Date value2) {
            addCriterion("Last_Login_Time not between", value1, value2, "last_Login_Time");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPIsNull() {
            addCriterion("Last_Login_IP is null");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPIsNotNull() {
            addCriterion("Last_Login_IP is not null");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPEqualTo(String value) {
            addCriterion("Last_Login_IP =", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPNotEqualTo(String value) {
            addCriterion("Last_Login_IP <>", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPGreaterThan(String value) {
            addCriterion("Last_Login_IP >", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPGreaterThanOrEqualTo(String value) {
            addCriterion("Last_Login_IP >=", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPLessThan(String value) {
            addCriterion("Last_Login_IP <", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPLessThanOrEqualTo(String value) {
            addCriterion("Last_Login_IP <=", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPLike(String value) {
            addCriterion("Last_Login_IP like", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPNotLike(String value) {
            addCriterion("Last_Login_IP not like", value, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPIn(List<String> values) {
            addCriterion("Last_Login_IP in", values, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPNotIn(List<String> values) {
            addCriterion("Last_Login_IP not in", values, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPBetween(String value1, String value2) {
            addCriterion("Last_Login_IP between", value1, value2, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLast_Login_IPNotBetween(String value1, String value2) {
            addCriterion("Last_Login_IP not between", value1, value2, "last_Login_IP");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountIsNull() {
            addCriterion("Login_Faild_Count is null");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountIsNotNull() {
            addCriterion("Login_Faild_Count is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountEqualTo(Integer value) {
            addCriterion("Login_Faild_Count =", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountNotEqualTo(Integer value) {
            addCriterion("Login_Faild_Count <>", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountGreaterThan(Integer value) {
            addCriterion("Login_Faild_Count >", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Login_Faild_Count >=", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountLessThan(Integer value) {
            addCriterion("Login_Faild_Count <", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountLessThanOrEqualTo(Integer value) {
            addCriterion("Login_Faild_Count <=", value, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountIn(List<Integer> values) {
            addCriterion("Login_Faild_Count in", values, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountNotIn(List<Integer> values) {
            addCriterion("Login_Faild_Count not in", values, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountBetween(Integer value1, Integer value2) {
            addCriterion("Login_Faild_Count between", value1, value2, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_CountNotBetween(Integer value1, Integer value2) {
            addCriterion("Login_Faild_Count not between", value1, value2, "login_Faild_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountIsNull() {
            addCriterion("Login_Faild_Lock_Count is null");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountIsNotNull() {
            addCriterion("Login_Faild_Lock_Count is not null");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountEqualTo(Integer value) {
            addCriterion("Login_Faild_Lock_Count =", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountNotEqualTo(Integer value) {
            addCriterion("Login_Faild_Lock_Count <>", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountGreaterThan(Integer value) {
            addCriterion("Login_Faild_Lock_Count >", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Login_Faild_Lock_Count >=", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountLessThan(Integer value) {
            addCriterion("Login_Faild_Lock_Count <", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountLessThanOrEqualTo(Integer value) {
            addCriterion("Login_Faild_Lock_Count <=", value, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountIn(List<Integer> values) {
            addCriterion("Login_Faild_Lock_Count in", values, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountNotIn(List<Integer> values) {
            addCriterion("Login_Faild_Lock_Count not in", values, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountBetween(Integer value1, Integer value2) {
            addCriterion("Login_Faild_Lock_Count between", value1, value2, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andLogin_Faild_Lock_CountNotBetween(Integer value1, Integer value2) {
            addCriterion("Login_Faild_Lock_Count not between", value1, value2, "login_Faild_Lock_Count");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 19 10:25:16 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table agent
     *
     * @mbg.generated Tue Oct 19 10:25:16 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}