package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class AgentEnterpriseUserCharge extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Enterprise_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String enterprise_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Enterprise_User_Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private Integer enterprise_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Order_Number
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String order_Number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Before_Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private BigDecimal before_Money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Money_Letter
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String money_Letter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Description
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Remark
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_enterprise_user_charge.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Id
     *
     * @return the value of agent_enterprise_user_charge.Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Id
     *
     * @param id the value for agent_enterprise_user_charge.Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Agent_No
     *
     * @return the value of agent_enterprise_user_charge.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Agent_No
     *
     * @param agent_No the value for agent_enterprise_user_charge.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Enterprise_No
     *
     * @return the value of agent_enterprise_user_charge.Enterprise_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getEnterprise_No() {
        return enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Enterprise_No
     *
     * @param enterprise_No the value for agent_enterprise_user_charge.Enterprise_No
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Enterprise_User_Id
     *
     * @return the value of agent_enterprise_user_charge.Enterprise_User_Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public Integer getEnterprise_User_Id() {
        return enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Enterprise_User_Id
     *
     * @param enterprise_User_Id the value for agent_enterprise_user_charge.Enterprise_User_Id
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setEnterprise_User_Id(Integer enterprise_User_Id) {
        this.enterprise_User_Id = enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Order_Number
     *
     * @return the value of agent_enterprise_user_charge.Order_Number
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getOrder_Number() {
        return order_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Order_Number
     *
     * @param order_Number the value for agent_enterprise_user_charge.Order_Number
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setOrder_Number(String order_Number) {
        this.order_Number = order_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Money
     *
     * @return the value of agent_enterprise_user_charge.Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Money
     *
     * @param money the value for agent_enterprise_user_charge.Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Before_Money
     *
     * @return the value of agent_enterprise_user_charge.Before_Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public BigDecimal getBefore_Money() {
        return before_Money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Before_Money
     *
     * @param before_Money the value for agent_enterprise_user_charge.Before_Money
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setBefore_Money(BigDecimal before_Money) {
        this.before_Money = before_Money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Money_Letter
     *
     * @return the value of agent_enterprise_user_charge.Money_Letter
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getMoney_Letter() {
        return money_Letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Money_Letter
     *
     * @param money_Letter the value for agent_enterprise_user_charge.Money_Letter
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setMoney_Letter(String money_Letter) {
        this.money_Letter = money_Letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Description
     *
     * @return the value of agent_enterprise_user_charge.Description
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Description
     *
     * @param description the value for agent_enterprise_user_charge.Description
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Remark
     *
     * @return the value of agent_enterprise_user_charge.Remark
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Remark
     *
     * @param remark the value for agent_enterprise_user_charge.Remark
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_enterprise_user_charge.Create_Date
     *
     * @return the value of agent_enterprise_user_charge.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_enterprise_user_charge.Create_Date
     *
     * @param create_Date the value for agent_enterprise_user_charge.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:25 CST 2021
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}