package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class AgentFee extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Id
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Operator
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Unit_Price
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private BigDecimal unit_Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Trade_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private String trade_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Message_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private String message_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Country_Number
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private String country_Number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_fee.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Id
     *
     * @return the value of agent_fee.Id
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Id
     *
     * @param id the value for agent_fee.Id
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Agent_No
     *
     * @return the value of agent_fee.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Agent_No
     *
     * @param agent_No the value for agent_fee.Agent_No
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Operator
     *
     * @return the value of agent_fee.Operator
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Operator
     *
     * @param operator the value for agent_fee.Operator
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Unit_Price
     *
     * @return the value of agent_fee.Unit_Price
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public BigDecimal getUnit_Price() {
        return unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Unit_Price
     *
     * @param unit_Price the value for agent_fee.Unit_Price
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setUnit_Price(BigDecimal unit_Price) {
        this.unit_Price = unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Trade_Type_Code
     *
     * @return the value of agent_fee.Trade_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public String getTrade_Type_Code() {
        return trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Trade_Type_Code
     *
     * @param trade_Type_Code the value for agent_fee.Trade_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setTrade_Type_Code(String trade_Type_Code) {
        this.trade_Type_Code = trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Message_Type_Code
     *
     * @return the value of agent_fee.Message_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public String getMessage_Type_Code() {
        return message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Message_Type_Code
     *
     * @param message_Type_Code the value for agent_fee.Message_Type_Code
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setMessage_Type_Code(String message_Type_Code) {
        this.message_Type_Code = message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Country_Number
     *
     * @return the value of agent_fee.Country_Number
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public String getCountry_Number() {
        return country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Country_Number
     *
     * @param country_Number the value for agent_fee.Country_Number
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setCountry_Number(String country_Number) {
        this.country_Number = country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_fee.Create_Date
     *
     * @return the value of agent_fee.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_fee.Create_Date
     *
     * @param create_Date the value for agent_fee.Create_Date
     *
     * @mbg.generated Tue Oct 19 10:29:40 CST 2021
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}