package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class ChannelDiversion extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Id
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Name
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Channel_No
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String channel_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Strategy_Type_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String strategy_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Strategy_Rule
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String strategy_Rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Status_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String status_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Description
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Remark
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Update_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private Date update_Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_diversion.Create_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Id
     *
     * @return the value of channel_diversion.Id
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Id
     *
     * @param id the value for channel_diversion.Id
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Name
     *
     * @return the value of channel_diversion.Name
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Name
     *
     * @param name the value for channel_diversion.Name
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Channel_No
     *
     * @return the value of channel_diversion.Channel_No
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getChannel_No() {
        return channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Channel_No
     *
     * @param channel_No the value for channel_diversion.Channel_No
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setChannel_No(String channel_No) {
        this.channel_No = channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Strategy_Type_Code
     *
     * @return the value of channel_diversion.Strategy_Type_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getStrategy_Type_Code() {
        return strategy_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Strategy_Type_Code
     *
     * @param strategy_Type_Code the value for channel_diversion.Strategy_Type_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setStrategy_Type_Code(String strategy_Type_Code) {
        this.strategy_Type_Code = strategy_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Strategy_Rule
     *
     * @return the value of channel_diversion.Strategy_Rule
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getStrategy_Rule() {
        return strategy_Rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Strategy_Rule
     *
     * @param strategy_Rule the value for channel_diversion.Strategy_Rule
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setStrategy_Rule(String strategy_Rule) {
        this.strategy_Rule = strategy_Rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Status_Code
     *
     * @return the value of channel_diversion.Status_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getStatus_Code() {
        return status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Status_Code
     *
     * @param status_Code the value for channel_diversion.Status_Code
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setStatus_Code(String status_Code) {
        this.status_Code = status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Description
     *
     * @return the value of channel_diversion.Description
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Description
     *
     * @param description the value for channel_diversion.Description
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Remark
     *
     * @return the value of channel_diversion.Remark
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Remark
     *
     * @param remark the value for channel_diversion.Remark
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Update_Date
     *
     * @return the value of channel_diversion.Update_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public Date getUpdate_Date() {
        return update_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Update_Date
     *
     * @param update_Date the value for channel_diversion.Update_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setUpdate_Date(Date update_Date) {
        this.update_Date = update_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_diversion.Create_Date
     *
     * @return the value of channel_diversion.Create_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_diversion.Create_Date
     *
     * @param create_Date the value for channel_diversion.Create_Date
     *
     * @mbg.generated Thu Jul 22 17:24:50 CST 2021
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}