package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.ReportAwait;
import com.hero.wireless.web.entity.send.ReportAwaitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IReportAwaitDAO<T extends ReportAwait> extends IDao<ReportAwait, ReportAwaitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int countByExample(ReportAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int deleteByExample(ReportAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int insert(ReportAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int insertList(List<ReportAwait> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int insertSelective(ReportAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    List<ReportAwait> selectByExample(ReportAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    ReportAwait selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ReportAwait record, @Param("example") ReportAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int updateByExample(@Param("record") ReportAwait record, @Param("example") ReportAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int updateByPrimaryKeySelective(ReportAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_await
     *
     * @mbg.generated Wed Oct 13 10:28:30 CST 2021
     */
    int updateByPrimaryKey(ReportAwait record);
}